
services:
  - type: web
    name: magajico-backend
    env: node
    region: oregon
    plan: free
    buildCommand: pnpm install && pnpm --filter @magajico/backend build
    startCommand: pnpm --filter @magajico/backend start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: REQUIRE_DB
        value: false
      - key: PORT
        sync: false
    healthCheckPath: /health
