services:
  - type: web
    name: magajico-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build --workspace=packages/shared && npm run build --workspace=@magajico/backend
    startCommand: node apps/backend/dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ML_SERVICE_URL
        value: http://127.0.0.1:8000
      - key: REQUIRE_DB
        value: true
      - key: PORT
        sync: false
    healthCheckPath: /health
