services:
  # Fastify Backend Service
  - type: web
    name: magajico-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: cd apps/backend && npx tsx src/index.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ML_SERVICE_URL
        sync: false
      - key: PORT
        value: 3001
    healthCheckPath: /health
    
  # FastAPI ML Service
  - type: web
    name: magajico-ml-service
    env: python
    region: oregon
    plan: free
    buildCommand: cd apps/backend/ml && pip install -r requirements.txt
    startCommand: cd apps/backend/ml && uvicorn api:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MODEL_PATH
        value: model_data.pkl
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
