
services:
  - type: web
    name: magajico-ml-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MODEL_PATH
        value: model_data.pkl
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
